FROM python:3.10-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY src/ui /app/src/ui
COPY src/ml /app/src/ml

COPY models /app/models

EXPOSE 8501

CMD ["streamlit", "run", "src/ui/streamlit_app.py", \
     "--server.address=0.0.0.0", \
     "--server.port=8501", \
     "--browser.serverAddress=0.0.0.0"]
